version: '3.1'

services:
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - puc-network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
  ticketin:
    image: ticketin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/ticketin"
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - mongodb
    networks:
      - puc-network

networks:
  puc-network:
    driver: bridge