server:
  port: 8080
spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      username: root
      password: example
      database: ticketin