server:
  port: 8080
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb://localhost/ticketindb
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG