server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tiketin
      gridfs:
        database: files
        bucket: images

  webflux:
    problemdetails:
      enabled: true

jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad
logging:
  level:
    root: INFO
    web: DEBUG
    com.example: DEBUG
